---
version: 3

tasks:
  default:
    desc: <-- You are here
    cmds:
      - task --list-all

  init:
    cmds:
      - pip install -r requirements.txt

  dev:
    cmds:
      - python main.py

  results:
    desc: Send test race results to API
    cmds:
      - bash test_data.sh
  
  test:
    desc: Run multi-client WebSocket broadcast tests (requires dev server running)
    cmds:
      - python test_multilient.py
  
  test:full:
    desc: Start dev server and run tests (opens test in new terminal)
    cmds:
      - task: dev
        background: true
      - sleep 3
      - python test_multilient.py
  
  reset:
    desc: Clear database and logs
    cmds:
      - rm -rf instance/race_results.db
      - rm -rf logs/*
