---
version: 3

tasks:
  default:
    desc: <-- You are here
    cmds:
      - task --list-all

  init:
    cmds:
      - pip install -r requirements.txt

  dev:
    cmds:
      - python main.py

  serve:
    cmds:
      - brew services start caddy || echo "Caddy already started"
      - gunicorn -w 4 -b 127.0.0.1:5000 main:app
      - caddy run --config Caddyfile


  results:
    cmds:
      - curl -XPOST http://127.0.0.1:5000/api/v1/reset
      - bash test_data.sh
  
  reset:
    cmds:
      - rm -rf instance/race_results.db
  
  stop:
    cmds:
      - caddy stop